"""initial_schema

Revision ID: 34245b952214
Revises: 
Create Date: 2026-04-26 21:24:25.360684
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision: str = '34245b952214'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('org_token', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('org_id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_org_token'), 'organizations', ['org_token'], unique=True)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('arch', sa.String(length=64), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], name=op.f('fk_agents_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('id', 'org_id', name='uq_agents_id_org_id'),
    sa.UniqueConstraint('org_id', 'hostname', name='uq_agents_org_id_hostname')
    )
    op.create_index(op.f('ix_agents_last_seen'), 'agents', ['last_seen'], unique=False)
    op.create_index(op.f('ix_agents_org_id'), 'agents', ['org_id'], unique=False)
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
                CREATE TYPE user_role AS ENUM ('admin', 'viewer', 'alert_manager');
            END IF;
        END
        $$;
        """
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'viewer', 'alert_manager', name='user_role', create_type=False), server_default='viewer', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], name=op.f('fk_users_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('anomaly_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id', 'org_id'], ['agents.id', 'agents.org_id'], name=op.f('fk_anomaly_events_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomaly_events'))
    )
    op.create_index(op.f('ix_anomaly_events_agent_id'), 'anomaly_events', ['agent_id'], unique=False)
    op.create_index('ix_anomaly_events_org_agent_created_at', 'anomaly_events', ['org_id', 'agent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_anomaly_events_org_id'), 'anomaly_events', ['org_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], name=op.f('fk_audit_log_org_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_org_id'), 'audit_log', ['org_id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('correlation_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('spike_metric', sa.String(length=32), nullable=False),
    sa.Column('spike_value', sa.Float(), nullable=False),
    sa.Column('spike_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlated_logs', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('correlation_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id', 'org_id'], ['agents.id', 'agents.org_id'], name=op.f('fk_correlation_events_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_correlation_events')),
    sa.UniqueConstraint('org_id', 'agent_id', 'spike_metric', 'spike_time', name='uq_correlation_events_org_agent_metric_time')
    )
    op.create_index(op.f('ix_correlation_events_agent_id'), 'correlation_events', ['agent_id'], unique=False)
    op.create_index('ix_correlation_events_org_created_at', 'correlation_events', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_correlation_events_org_id'), 'correlation_events', ['org_id'], unique=False)
    op.create_index(op.f('ix_correlation_events_spike_time'), 'correlation_events', ['spike_time'], unique=False)
    op.create_table('forecast_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('exceed_in_hours', sa.Float(), nullable=True),
    sa.Column('forecast_points', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_sent', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id', 'org_id'], ['agents.id', 'agents.org_id'], name=op.f('fk_forecast_alerts_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_alerts'))
    )
    op.create_index(op.f('ix_forecast_alerts_agent_id'), 'forecast_alerts', ['agent_id'], unique=False)
    op.create_index(op.f('ix_forecast_alerts_metric'), 'forecast_alerts', ['metric'], unique=False)
    op.create_index('ix_forecast_alerts_org_agent_created_at', 'forecast_alerts', ['org_id', 'agent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_forecast_alerts_org_id'), 'forecast_alerts', ['org_id'], unique=False)
    op.create_table('log_entry',
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id', 'org_id'], ['agents.id', 'agents.org_id'], name=op.f('fk_log_entry_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'id', name=op.f('pk_log_entry'))
    )
    op.create_index(op.f('ix_log_entry_agent_id'), 'log_entry', ['agent_id'], unique=False)
    op.create_index(op.f('ix_log_entry_level'), 'log_entry', ['level'], unique=False)
    op.create_index('ix_log_entry_org_agent_level_source_time', 'log_entry', ['org_id', 'agent_id', 'level', 'source', 'time'], unique=False)
    op.create_index('ix_log_entry_org_agent_time', 'log_entry', ['org_id', 'agent_id', 'time'], unique=False)
    op.create_index(op.f('ix_log_entry_org_id'), 'log_entry', ['org_id'], unique=False)
    op.create_index(op.f('ix_log_entry_source'), 'log_entry', ['source'], unique=False)
    op.create_table('metrics',
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=False),
    sa.Column('memory', sa.Float(), nullable=False),
    sa.Column('disk', sa.Float(), nullable=False),
    sa.Column('net_in', sa.Float(), nullable=False),
    sa.Column('net_out', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id', 'org_id'], ['agents.id', 'agents.org_id'], name=op.f('fk_metrics_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'agent_id', 'org_id', name=op.f('pk_metrics'))
    )
    op.create_index('ix_metrics_org_agent_time', 'metrics', ['org_id', 'agent_id', 'time'], unique=False)
    op.create_index(op.f('ix_metrics_org_id'), 'metrics', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_org_id'), table_name='metrics')
    op.drop_index('ix_metrics_org_agent_time', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_log_entry_source'), table_name='log_entry')
    op.drop_index(op.f('ix_log_entry_org_id'), table_name='log_entry')
    op.drop_index('ix_log_entry_org_agent_time', table_name='log_entry')
    op.drop_index('ix_log_entry_org_agent_level_source_time', table_name='log_entry')
    op.drop_index(op.f('ix_log_entry_level'), table_name='log_entry')
    op.drop_index(op.f('ix_log_entry_agent_id'), table_name='log_entry')
    op.drop_table('log_entry')
    op.drop_index(op.f('ix_forecast_alerts_org_id'), table_name='forecast_alerts')
    op.drop_index('ix_forecast_alerts_org_agent_created_at', table_name='forecast_alerts')
    op.drop_index(op.f('ix_forecast_alerts_metric'), table_name='forecast_alerts')
    op.drop_index(op.f('ix_forecast_alerts_agent_id'), table_name='forecast_alerts')
    op.drop_table('forecast_alerts')
    op.drop_index(op.f('ix_correlation_events_spike_time'), table_name='correlation_events')
    op.drop_index(op.f('ix_correlation_events_org_id'), table_name='correlation_events')
    op.drop_index('ix_correlation_events_org_created_at', table_name='correlation_events')
    op.drop_index(op.f('ix_correlation_events_agent_id'), table_name='correlation_events')
    op.drop_table('correlation_events')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_org_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_anomaly_events_org_id'), table_name='anomaly_events')
    op.drop_index('ix_anomaly_events_org_agent_created_at', table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_agent_id'), table_name='anomaly_events')
    op.drop_table('anomaly_events')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.execute("DROP TYPE IF EXISTS user_role")
    op.drop_index(op.f('ix_agents_org_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_last_seen'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_org_token'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
